package mil.emp3.api.events;

import mil.emp3.api.enums.KMLSEventEnum;
import mil.emp3.api.interfaces.IKMLS;
import mil.emp3.api.interfaces.IMap;

/**
 * Event is generated by the EMP Core component to report the status of client application installed KMLS Service. Client application
 * ise IMap.addMapService to install the Map Service. Client application should implement a Listener that extends IKMLSEventListener and
 * provide a reference to it when KMLS service object is created.
 */
public abstract class KMLSEvent extends Event<KMLSEventEnum, IKMLS> {
    private final IMap clientMap;
    protected KMLSEvent(KMLSEventEnum eEvent, IKMLS oTarget, IMap clientMap) {
        super(eEvent, oTarget);
        this.clientMap = clientMap;
    }

    public IMap getClientMap() {
        return clientMap;
    }
}
