package mil.emp3.api.events;

import mil.emp3.api.enums.KMLSEventEnum;
import mil.emp3.api.interfaces.IKMLS;
import mil.emp3.api.interfaces.IMap;
import mil.emp3.api.interfaces.IMapService;

/**
 * Event is generated by the EMP Core component to report the status of client application installed {@link mil.emp3.api.KMLS} Service. Client
 * applications use {@link mil.emp3.api.interfaces.IMap#addMapService(IMapService)} to install the Map Service. Client applications should
 * implement a Listener that extends {@link mil.emp3.api.listeners.IKMLSEventListener} and provide a reference to it when {@link mil.emp3.api.KMLS}
 * service object is created.
 */
public abstract class KMLSEvent extends Event<KMLSEventEnum, IKMLS> {
    private final IMap clientMap;
    protected KMLSEvent(KMLSEventEnum eEvent, IKMLS oTarget, IMap clientMap) {
        super(eEvent, oTarget);
        this.clientMap = clientMap;
    }

    public IMap getClientMap() {
        return clientMap;
    }
}
