package mil.emp3.api.enums;

import mil.emp3.api.interfaces.IEventEnum;

/**
 * This class enumerates the different events that can be generated by a camera.
 */
public enum CameraEventEnum implements IEventEnum {
    /**
     * This enumerated value indicates that the target camera is currently in motion. One or more camera settings have been changed.
     */
    CAMERA_IN_MOTION,

    /**
     * This enumerated value indicates that the target camera has stopped moving. The event contains the cameras final settings.
     */
    CAMERA_MOTION_STOPPED
}
