package mil.emp3.api.enums;

import mil.emp3.api.interfaces.IEventEnum;

/**
 * Type of event generated by a {@link mil.emp3.api.Camera}
 */
public enum CameraEventEnum implements IEventEnum {
    /**
     * Camera is currently in motion, i.e one or more camera settings have been changed.
     */
    CAMERA_IN_MOTION,

    /**
     * Camera has stopped moving.
     */
    CAMERA_MOTION_STOPPED
}
