package mil.emp3.api.enums;

import mil.emp3.api.interfaces.IEventEnum;

/**
 * Type of event generated by a {@link mil.emp3.api.abstracts.Container}.
 */
public enum ContainerEventEnum implements IEventEnum {
    /**
     * One or more objects/containers was added to the container.
     */
    OBJECT_ADDED,
    /**
     * One or more objects/containers was removed from the container.
     */
    OBJECT_REMOVED
}
