package mil.emp3.api.enums;

import mil.emp3.api.interfaces.IEventEnum;

/**
 * Type of event generated by a {@link mil.emp3.api.LookAt}
 */

public enum LookAtEventEnum implements IEventEnum {
    /**
     * Target lookAt is currently in motion. One or more camera settings have been changed.
     */
    LOOKAT_IN_MOTION,

    /**
     * Target lookAt has stopped moving. The event contains the cameras final settings.
     */
    LOOKAT_MOTION_STOPPED

}
