package mil.emp3.api.enums;

import mil.emp3.api.interfaces.IEventEnum;
/**
 * Types user interaction events that can be generated by a map based on gestures.
 */
public enum UserInteractionEventEnum implements IEventEnum {
    /**
     * Object was clicked.
     */
    CLICKED,

    /**
     * Object was double clicked.
     */
    DOUBLE_CLICKED,

    /**
     * Object was long pressed.
     */
    LONG_PRESS,
    //PRESS_RELEASE,

    /**
     * Feature or map was dragged.
     */
    DRAG,
    /**
     * Drag operation has completed, i.e. user lifted the finger.
     */
    DRAG_COMPLETE
}
