
include $(CLEAR_VARS)
LOCAL_MODULE := jnimsp_ccs
LOCAL_SHARED_LIBRARIES := MSPdtcc MSPCoordinateConversionService
LOCAL_CPP_FEATURES := rtti exceptions
LOCAL_C_INCLUDES := $(INCLUDES) $(DTCCINCS) $(JNIINCS)
LOCAL_CFLAGS := $(GEO_TRANS_CFLAGS)
LOCAL_SRC_FILES := $(SRCS) $(JNISRCS)
include $(BUILD_SHARED_LIBRARY)
