
include $(CLEAR_VARS)
LOCAL_MODULE := MSPdtcc
LOCAL_CPP_FEATURES := rtti exceptions
LOCAL_C_INCLUDES := $(INCLUDES) $(DTCCINCS)
LOCAL_CFLAGS := $(GEO_TRANS_CFLAGS)
LOCAL_SRC_FILES := $(DTCCSRCS) $(CCSERVICESRCS)
include $(BUILD_SHARED_LIBRARY)


