package mil.emp3.mapengine.events;

import mil.emp3.api.enums.MapEventEnum;
import mil.emp3.api.enums.MapStateEnum;
import mil.emp3.api.events.Event;
import mil.emp3.mapengine.interfaces.IMapInstance;

/**
 * This class implements the Map Instance State Change Event. It must be generated by all map engine
 * instances when the state of the map changes. See {@link MapStateEnum}.
 * All events of this type are handled by the EMP core code.
 */
public class MapInstanceStateChangeEvent extends Event<MapEventEnum, IMapInstance> {
    private final MapStateEnum eNewState;

    /**
     * This constructor must be called by the map engines to creates a MapInstanceUserInteractionEvent event
     * @param oMapInstance The actual map instance. The this property of the object that implements the IMapInstance interface.
     * @param eState The enumerated value of the new state of the map instance. See {@link MapStateEnum}.
     */
    public MapInstanceStateChangeEvent(IMapInstance oMapInstance,
            MapStateEnum eState) {
        super(MapEventEnum.STATE_CHANGE, oMapInstance);
        this.eNewState = eState;
    }

    public MapStateEnum getState() {
        return this.eNewState;
    }
}
