package mil.emp3.mapengine.events;

import mil.emp3.api.enums.MapFeatureEventEnum;
import mil.emp3.api.events.Event;
import mil.emp3.api.interfaces.IFeature;
import mil.emp3.mapengine.interfaces.IMapInstance;

/**
 * MapInstanceFeatureAdded event must be must be generated by all map engines when a feature is added to the map. See {@link MapFeatureEventEnum}
 * All events of this type are handled by the EMP core code.
 */
public class MapInstanceFeatureAddedEvent extends Event<MapFeatureEventEnum, IMapInstance> {
    final private IFeature feature;

    /**
     * This constructor must be called by the map engines to create a MapInstanceUserInteractionEvent event
     * @param mapInstance The actual map instance. The this property of the object that implements the IMapInstance interface.
     * @param event The feature event generated. See {@link MapFeatureEventEnum}.
     * @param feature The feature this event is associated with. See {@link IFeature}.
     */
    public MapInstanceFeatureAddedEvent(IMapInstance mapInstance, MapFeatureEventEnum event, IFeature feature) {
        super(event, mapInstance);
        this.feature = feature;
    }

    /**
     * Returns the feature for which the event was generated.
     * @return the feature added
     */
    public IFeature getFeature() {
        return feature;
    }
}
