/**
 * Events generated by map engine instance for use by EMP3 Core. You will need to use these only if you are
 * developing code for a new map engine. Application developers using EMP3 API should not be bothered with these events.
 */
package mil.emp3.mapengine.events;