// CLASSIFICATION: UNCLASSIFIED

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class geotrans3_jni_JNICoordinateConversionService */

#ifndef _Included_geotrans3_jni_JNICoordinateConversionService
#define _Included_geotrans3_jni_JNICoordinateConversionService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     geotrans3_jni_JNICoordinateConversionService
 * Method:    jniCreate
 * Signature: (Ljava/lang/String;Lmsp/ccs/parameters/CoordinateSystemParameters;Ljava/lang/String;Lmsp/ccs/parameters/CoordinateSystemParameters;)J
 */
JNIEXPORT jlong JNICALL Java_geotrans3_jni_JNICoordinateConversionService_jniCreate
  (JNIEnv *, jobject, jstring, jobject, jstring, jobject);

/*
 * Class:     geotrans3_jni_JNICoordinateConversionService
 * Method:    jniDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_geotrans3_jni_JNICoordinateConversionService_jniDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     geotrans3_jni_JNICoordinateConversionService
 * Method:    jniConvertSourceToTarget
 * Signature: (JLmsp/ccs/coordinates/CoordinateTuple;Lmsp/ccs/coordinates/Accuracy;Lmsp/ccs/coordinates/CoordinateTuple;Lmsp/ccs/coordinates/Accuracy;)V
 */
JNIEXPORT void JNICALL Java_geotrans3_jni_JNICoordinateConversionService_jniConvertSourceToTarget
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     geotrans3_jni_JNICoordinateConversionService
 * Method:    jniConvertTargetToSource
 * Signature: (JLmsp/ccs/coordinates/CoordinateTuple;Lmsp/ccs/coordinates/Accuracy;Lmsp/ccs/coordinates/CoordinateTuple;Lmsp/ccs/coordinates/Accuracy;)V
 */
JNIEXPORT void JNICALL Java_geotrans3_jni_JNICoordinateConversionService_jniConvertTargetToSource
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     geotrans3_jni_JNICoordinateConversionService
 * Method:    jniConvertSourceToTargetCollection
 * Signature: (JLjava/util/Collection;Ljava/util/Collection;Ljava/util/Collection;Ljava/util/Collection;)V
 */
JNIEXPORT void JNICALL Java_geotrans3_jni_JNICoordinateConversionService_jniConvertSourceToTargetCollection
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     geotrans3_jni_JNICoordinateConversionService
 * Method:    jniConvertTargetToSourceCollection
 * Signature: (JLjava/util/Collection;Ljava/util/Collection;Ljava/util/Collection;Ljava/util/Collection;)V
 */
JNIEXPORT void JNICALL Java_geotrans3_jni_JNICoordinateConversionService_jniConvertTargetToSourceCollection
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     geotrans3_jni_JNICoordinateConversionService
 * Method:    jniGetDatumLibrary
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_geotrans3_jni_JNICoordinateConversionService_jniGetDatumLibrary
  (JNIEnv *, jobject, jlong);

/*
 * Class:     geotrans3_jni_JNICoordinateConversionService
 * Method:    jniGetEllipsoidLibrary
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_geotrans3_jni_JNICoordinateConversionService_jniGetEllipsoidLibrary
  (JNIEnv *, jobject, jlong);

/*
 * Class:     geotrans3_jni_JNICoordinateConversionService
 * Method:    jniGetServiceVersion
 * Signature: (J)I
 */
JNIEXPORT jdouble JNICALL Java_geotrans3_jni_JNICoordinateConversionService_jniGetServiceVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     geotrans3_jni_JNICoordinateConversionService
 * Method:    jniGetDatum
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_geotrans3_jni_JNICoordinateConversionService_jniGetDatum
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     geotrans3_jni_JNICoordinateConversionService
 * Method:    jniGetCoordinateSystem
 * Signature: (JI)Lmsp/ccs/parameters/CoordinateSystemParameters;
 */
JNIEXPORT jobject JNICALL Java_geotrans3_jni_JNICoordinateConversionService_jniGetCoordinateSystem
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif

// CLASSIFICATION: UNCLASSIFIED
