// CLASSIFICATION: UNCLASSIFIED

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class geotrans3_jni_JNIDatumLibrary */

#ifndef _Included_geotrans3_jni_JNIDatumLibrary
#define _Included_geotrans3_jni_JNIDatumLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     geotrans3_jni_JNIDatumLibrary
 * Method:    jniDefineDatum
 * Signature: (JILjava/lang/String;Ljava/lang/String;Ljava/lang/String;DDDDDDDDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_geotrans3_jni_JNIDatumLibrary_jniDefineDatum
  (JNIEnv *, jobject, jlong, jint, jstring, jstring, jstring, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     geotrans3_jni_JNIDatumLibrary
 * Method:    jniRemoveDatum
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_geotrans3_jni_JNIDatumLibrary_jniRemoveDatum
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     geotrans3_jni_JNIDatumLibrary
 * Method:    jniGetDatumCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_geotrans3_jni_JNIDatumLibrary_jniGetDatumCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     geotrans3_jni_JNIDatumLibrary
 * Method:    jniGetDatumIndex
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_geotrans3_jni_JNIDatumLibrary_jniGetDatumIndex
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     geotrans3_jni_JNIDatumLibrary
 * Method:    jniGetDatumInfo
 * Signature: (JJ)Lmsp/ccs/gui/Info;
 */
JNIEXPORT jobject JNICALL Java_geotrans3_jni_JNIDatumLibrary_jniGetDatumInfo
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     geotrans3_jni_JNIDatumValidRectangle
 * Method:    jniGetDatumValidRectangle
 * Signature: (JJ)Lmsp/ccs/gui/AOI;
 */
JNIEXPORT jobject JNICALL Java_geotrans3_jni_JNIDatumLibrary_jniGetDatumValidRectangle
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif

// CLASSIFICATION: UNCLASSIFIED
