// CLASSIFICATION: UNCLASSIFIED

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class geotrans3_jni_JNIEllipsoidLibrary */

#ifndef _Included_geotrans3_jni_JNIEllipsoidLibrary
#define _Included_geotrans3_jni_JNIEllipsoidLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     geotrans3_jni_JNIEllipsoidLibrary
 * Method:    jniDefineEllipsoid
 * Signature: (JLjava/lang/String;Ljava/lang/String;DD)V
 */
JNIEXPORT void JNICALL Java_geotrans3_jni_JNIEllipsoidLibrary_jniDefineEllipsoid
  (JNIEnv *, jobject, jlong, jstring, jstring, jdouble, jdouble);

/*
 * Class:     geotrans3_jni_JNIEllipsoidLibrary
 * Method:    jniRemoveEllipsoid
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_geotrans3_jni_JNIEllipsoidLibrary_jniRemoveEllipsoid
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     geotrans3_jni_JNIEllipsoidLibrary
 * Method:    jniGetEllipsoidCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_geotrans3_jni_JNIEllipsoidLibrary_jniGetEllipsoidCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     geotrans3_jni_JNIEllipsoidLibrary
 * Method:    jniGetEllipsoidIndex
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_geotrans3_jni_JNIEllipsoidLibrary_jniGetEllipsoidIndex
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     geotrans3_jni_JNIEllipsoidLibrary
 * Method:    jniGetEllipsoidInfo
 * Signature: (JJ)Lmsp/ccs/gui/Info;
 */
JNIEXPORT jobject JNICALL Java_geotrans3_jni_JNIEllipsoidLibrary_jniGetEllipsoidInfo
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif

// CLASSIFICATION: UNCLASSIFIED
